import 'package:flutter/material.dart';

import '../../core/date_utils.dart';
import '../../core/models.dart';
import '../../services/admin_service.dart';
import '../shared/message_card.dart';

class ReportsPage extends StatefulWidget{final AdminSession session; final AdminService service; const ReportsPage({super.key, required this.session, required this.service}); @override State<ReportsPage> createState()=>_ReportsPageState();}
class _ReportsPageState extends State<ReportsPage>{late DateTime month; late Future<SimpleItem> future; @override void initState(){super.initState(); month=DateTime(DateTime.now().year, DateTime.now().month); future=widget.service.loadMonthlyReport(widget.session, month);} void setMonth(DateTime v)=>setState((){month=DateTime(v.year,v.month); future=widget.service.loadMonthlyReport(widget.session, month);}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Laporan Ringkas'), actions:[IconButton(onPressed:()=>setMonth(DateTime(month.year,month.month-1)), icon:const Icon(Icons.chevron_left_rounded)), IconButton(onPressed:()=>setMonth(DateTime(month.year,month.month+1)), icon:const Icon(Icons.chevron_right_rounded))]), body:FutureBuilder<SimpleItem>(future:future,builder:(context,snap){return ListView(padding:const EdgeInsets.all(18), children:[Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.calendar_month_rounded)), title:Text(AdminDateUtils.monthLabel(month), style:const TextStyle(fontWeight:FontWeight.w900)), subtitle:const Text('Ringkasan bulan berjalan'))), const SizedBox(height:12), if(snap.connectionState==ConnectionState.waiting) const Padding(padding:EdgeInsets.all(32), child:Center(child:CircularProgressIndicator())) else if(snap.hasError) MessageCard(title:'Gagal memuat laporan', message:snap.error.toString(), icon:Icons.error_outline_rounded) else Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.insert_chart_rounded)), title:Text(snap.data?.title??'-', style:const TextStyle(fontWeight:FontWeight.w900)), subtitle:Text(snap.data?.subtitle??'-')))]);}));}
